export interface EducationProvider {
  cil_deti: boolean | null;
  cil_dospeli: boolean | null;
  cil_lektori: boolean | null;
  cil_odbornici: boolean | null;
  cil_seniori: boolean | null;
  cil_tymy_autoskoly: boolean | null;
  cil_tymy_firmy: boolean | null;
  cil_tymy_skoly: boolean | null;
  created_at: string;
  forma_online: boolean | null;
  forma_zive: boolean | null;
  id: number;
  kontakty_email: string | null;
  kontakty_facebook: string | null;
  kontakty_instagram: string | null;
  kontakty_telefon: string | null;
  kontakty_web: string | null;
  lokalita_kraj: string | null;
  lokalita_vsude: boolean | null;
  nazev: string;
  podnazev: string | null;
  pristupnost_bezbarierove: boolean | null;
  pristupnost_neslysici: boolean | null;
  pristupnost_nevidomi: boolean | null;
  soukromi_soukrome: boolean | null;
  soukromi_verejne: boolean | null;
  terennost_maskovani: boolean | null;
  terennost_teorie: boolean | null;
  terennost_vr: boolean | null;
  typ_hra: boolean | null;
  typ_kniha: boolean | null;
  typ_kurz: boolean | null;
  typ_podcast: boolean | null;
  typ_udalost: boolean | null;
  typ_web: boolean | null;
  zamereni_hory: boolean | null;
  zamereni_miminko: boolean | null;
  zamereni_voda: boolean | null;
  zamereni_zdravotnik: boolean | null;
}
